version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  chat_service:
    build:
      context: ./chat_service
    container_name: chat_service
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  knowledge_service:
    build:
      context: ./knowledge_service
    container_name: knowledge_service
    ports:
      - "8001:8001"
    depends_on:
      - mongo

  search_service:
    build:
      context: ./search_service
    container_name: search_service
    ports:
      - "8002:8002"
    depends_on:
      - mongo

  history_service:
    build:
      context: ./history_service
    container_name: history_service
    ports:
      - "8003:8003"
    depends_on:
      - mongo
